name 'web_node'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures web_node'
long_description 'Installs/Configures web_node'
version '0.1.0'
depends 'base'
